#!/usr/bin/with-contenv bash
SUBJECT="/C=GB/ST=SM/L=Bath/O=dengro.com/OU=DenGro Ltd/CN=*"
if [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; then
else
openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
fi


