#!/usr/bin/with-contenv bash
SUBJECT="/C=US/ST=CA/L=Nowhere/O=example.com/OU=ACME/CN=*"
if [[ -f /config/keys/cert.key && -f /config/keys/cert.crt ]]; then
echo "keys found in /config/keys"
else
openssl req -new -x509 -days 3650 -nodes -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "$SUBJECT"
fi
